//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Reclamo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WU_TablaDato
    {
        public string Relacion { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
        public int Orden { get; set; }
    }
}
